<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find semes_robot)/urdf/include/common_properties.urdf.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/mobile_robot.gazebo.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/mobile_robot.transmission.xacro" />
  
  <xacro:include filename="$(find semes_robot)/urdf/include/imu.gazebo.urdf.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/nanoscan_pro3.urdf.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/d435_3d_camera.urdf.xacro" />
  <xacro:property name="d435_camera" default="true" />

  <xacro:property name="deg_to_rad" value="0.017453293" />

  <xacro:property name="mobile_robot_base_mass" value="58.0" />

  <xacro:property name="mobile_robot_act_wheel_radius" value="0.0625" />
  <xacro:property name="mobile_robot_act_wheel_width" value="0.032" />
  <xacro:property name="mobile_robot_act_wheel_mass" value="1.0" />
  <xacro:property name="mobile_robot_act_wheel_dx" value="0.037646" />
  <xacro:property name="mobile_robot_act_wheel_dy" value="0.222604" />  <!-- 주행 휠 사이 거리 수정 / y좌표 : 0.222604, -0.222604 -->

  <xacro:property name="mobile_robot_caster_wheel_radius" value="${mobile_robot_act_wheel_radius}" /> <!-- 캐스터 휠 반지름 -->
  <xacro:property name="mobile_robot_caster_wheel_width" value="${mobile_robot_act_wheel_width}" /> <!-- 캐스터 휠 두께 : 10.3cm -->
  <xacro:property name="mobile_robot_caster_wheel_mass" value="${mobile_robot_act_wheel_mass}" />
  <xacro:property name="mobile_robot_caster_wheel_dx" value="-0.0382" />
  <xacro:property name="mobile_robot_caster_wheel_dy" value="0" />
  <xacro:property name="mobile_robot_caster_wheel_dz" value="-0.094" />
  <xacro:property name="mobile_robot_front_caster_wheel_base_dx" value="0.341346" />
  <xacro:property name="mobile_robot_back_caster_wheel_base_dx" value="-0.270154" />
  <xacro:property name="mobile_robot_caster_wheel_base_dy" value="0.203" /> <!-- 캐스터 휠 사이 거리 수정 / y좌표 : 0.203, -0.203 -->
  <xacro:property name="mobile_robot_caster_wheel_base_dz" value="${mobile_robot_caster_wheel_radius-mobile_robot_caster_wheel_dz}" />

  <xacro:property name="imu_stdev" value="0.00017" />

  <xacro:macro name="actuated_wheel" params="locationprefix locationright">
    <joint name="${locationprefix}_wheel_joint" type="fixed">
      <origin xyz="0.0 ${-mobile_robot_act_wheel_dy * locationright} ${mobile_robot_act_wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="${locationprefix}_wheel_link" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="20.0" />
    </joint>

    <link name="${locationprefix}_wheel_link">
      <xacro:cylinder_inertial mass="${mobile_robot_act_wheel_mass}" radius="${mobile_robot_act_wheel_radius}" length="${mobile_robot_act_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/visual/wheel.stl" />
        </geometry>
        <xacro:insert_block name="material_dark_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/visual/wheel.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${locationprefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="caster_wheel" params="locationprefix locationright wheel_base_dx">
    <!-- caster hub -->
    <joint name="${locationprefix}_caster_rotation_joint" type="fixed">
      <origin xyz="${wheel_base_dx} ${-mobile_robot_caster_wheel_base_dy * locationright} ${mobile_robot_caster_wheel_base_dz}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="${locationprefix}_caster_rotation_link" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="${locationprefix}_caster_rotation_link">
      <inertial>
        <!-- <origin xyz="0 0 -0.042500000044" rpy="${0.5 * pi} ${24 * deg_to_rad} ${1.5 * pi}" /> -->
        <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
        <mass value="0.3097539019" />
        <inertia
          ixx="0.0005844517978"
          ixy="0"
          ixz="0"
          iyy="0.00052872551237"
          iyz="0"
          izz="0.00017923555074" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/visual/caster_wheel_base.stl" />
        </geometry>
        <xacro:insert_block name="material_silver" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/collision/caster_wheel_base.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${locationprefix}_caster_rotation_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- caster wheel -->
    <joint name="${locationprefix}_caster_wheel_joint" type="fixed">
      <origin xyz="${mobile_robot_caster_wheel_dx} ${-mobile_robot_caster_wheel_dy * locationright} ${mobile_robot_caster_wheel_dz}" rpy="0 0 0" />
      <parent link="${locationprefix}_caster_rotation_link" />
      <child link="${locationprefix}_caster_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="${locationprefix}_caster_wheel_link">
      <xacro:cylinder_inertial mass="${mobile_robot_caster_wheel_mass}" radius="${mobile_robot_caster_wheel_radius}" length="${mobile_robot_caster_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/visual/wheel.stl" />
        </geometry>
        <xacro:insert_block name="material_dark_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/visual/wheel.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${locationprefix}_caster_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>

 <!-- wheels -->
    <xacro:actuated_wheel locationprefix="left" locationright="-1"/>
    <xacro:actuated_wheel locationprefix="right" locationright="1"/>
    <xacro:caster_wheel locationprefix="fl" locationright="-1" wheel_base_dx="${mobile_robot_front_caster_wheel_base_dx}"/>
    <xacro:caster_wheel locationprefix="fr" locationright="1" wheel_base_dx="${mobile_robot_front_caster_wheel_base_dx}"/>
    <xacro:caster_wheel locationprefix="bl" locationright="-1" wheel_base_dx="${mobile_robot_back_caster_wheel_base_dx}"/>
    <xacro:caster_wheel locationprefix="br" locationright="1" wheel_base_dx="${mobile_robot_back_caster_wheel_base_dx}"/>

    <joint name="base_link_surface_joint" type="fixed">
      <origin xyz="${mobile_robot_act_wheel_dx} 0 0.352" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="surface" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="surface"/>

  <!-- robot body -->
  <xacro:macro name="mobile_robot">
    <!-- <link name="base_footprint" /> -->

    <!-- <joint name="base_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint> -->

    <link name="base_link">
      <xacro:box_inertial mass="${mobile_robot_base_mass}" x="0.9" y="0.58" z="0.3">
        <origin xyz="${mobile_robot_act_wheel_dx} 0 0.20" rpy="0 0 0" />
      </xacro:box_inertial>
      <visual>
        <origin xyz="${mobile_robot_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/visual/mir_100_base.stl" />
        </geometry>
        <xacro:insert_block name="material_white" />
      </visual>
      <collision>
        <origin xyz="${mobile_robot_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mir_description/meshes/collision/mir_100_base.stl" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="base_link">
      <material>Gazebo/White</material>
    </gazebo>

    <!-- IMU -->
    <joint name="base_link_to_imu_joint" type="fixed">
      <parent link="base_link" />
      <child link="imu_link" />
      <!-- same as real MiR -->
      <origin xyz="0.0 0.0 0.353" rpy="0 0 ${-pi/2}" />  
    </joint>

    <link name="imu_link" />

    <xacro:imu_gazebo link="imu_link" imu_topic="imu_data" update_rate="50.0" stdev="${imu_stdev}" />

    <!-- Create an alias for imu_link. This is necessary because the real MiR's
         TF has imu_link, but the imu_data topic is published in the imu_frame
         frame. -->
    <joint name="imu_link_to_imu_frame_joint" type="fixed">
      <parent link="imu_link" />
      <child link="imu_frame" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="imu_frame" />

    <!-- 3D Camera -->
    <xacro:if value="${d435_camera}">
      <joint name="base_link_to_left_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="left_camera_link" />
        <origin xyz="0.385 0.0425 0.11774" rpy="${pi/2 - 0.3274} -0.0873 -0.3503" />  
      </joint>

      <xacro:d435_3d_camera link="left_camera_link"  topic="/camera/depth/color/points"/> 
      
      <joint name="camera_link_to_left_camera_depth_frame_joint" type="fixed">
        <parent link="left_camera_link" />
        <child link="left_camera_depth_frame" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </joint>

      <link name="left_camera_depth_frame" /> 

      <joint name="base_link_to_right_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="right_camera_link" />
        <origin xyz="0.385 -0.0425 0.11774" rpy="${pi/2 + 0.3274} -0.0873 0.3503" />  
      </joint>

      <xacro:d435_3d_camera link="right_camera_link"  topic="/camera/depth/color/points"/>
      
      <joint name="camera_link_to_right_camera_depth_frame_joint" type="fixed">
        <parent link="right_camera_link" />
        <child link="right_camera_depth_frame" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </joint>

      <link name="right_camera_depth_frame" /> 
    </xacro:if>

    <!-- Laser scanners -->
    <joint name="base_link_to_front_laser_joint" type="fixed">
      <parent link="base_link" />
      <child link="front_laser_link" />
      <origin xyz="0.312495 0.210005 0.30857" rpy="0.0 0.0 ${0.25 * pi}" />  <!-- from visually matching up the meshes of the MiR and the laser scanner -->
    </joint>
    <xacro:nanoscan_pro3 link="front_laser_link" topic="f_scan"/>

    <joint name="base_link_to_back_laser_joint" type="fixed">
      <parent link="base_link" />
      <child link="back_laser_link" /> 
      <origin xyz="-0.312495 -0.210005 0.10857" rpy="0.0 0.0 ${-0.75 * pi}" />  <!-- from visually matching up the meshes of the MiR and the laser scanner -->
    </joint>
    <xacro:nanoscan_pro3 link="back_laser_link" topic="b_scan"/>

    <xacro:mobile_robot_wheel_transmissions/>
    
  </xacro:macro>

</robot>
