<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find semes_robot)/urdf/include/common_properties.urdf.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/imu.gazebo.urdf.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/mobile_robot.gazebo.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/mobile_robot.transmission.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/nanoscan_pro3.urdf.xacro" />
  <!-- <xacro:include filename="$(find semes_robot)/urdf/include/d435_3d_camera.urdf.xacro" /> -->

  <xacro:include filename="$(find semes_robot)/urdf/include/actuated_wheel.urdf.xacro" />
  <xacro:include filename="$(find semes_robot)/urdf/include/caster_wheel.urdf.xacro" />

  <xacro:property name="d435_camera" default="true" />

  <xacro:property name="deg_to_rad" value="0.017453293" />

  <xacro:property name="mobile_robot_base_mass" value="58.0" />

  <xacro:property name="mobile_robot_act_wheel_radius" value="0.06" />  <!-- 0.0625 -> 0.06  -->
  <xacro:property name="mobile_robot_act_wheel_width" value="0.032" /> 
  <xacro:property name="mobile_robot_act_wheel_mass" value="1.0" />
  <xacro:property name="mobile_robot_act_wheel_dx" value="0.01" /> <!-- 0.037646 -> 0.01  -->
  <xacro:property name="mobile_robot_act_wheel_dy" value="0.26" />  <!-- 0.222604 -> 0.26  -->

  <xacro:property name="mobile_robot_caster_wheel_radius" value="${mobile_robot_act_wheel_radius}" />
  <xacro:property name="mobile_robot_caster_wheel_width" value="${mobile_robot_act_wheel_width}" />
  <xacro:property name="mobile_robot_caster_wheel_mass" value="${mobile_robot_act_wheel_mass}" />
  <xacro:property name="mobile_robot_caster_wheel_dx" value="-0.0382" />
  <xacro:property name="mobile_robot_caster_wheel_dy" value="0" />
  <xacro:property name="mobile_robot_caster_wheel_dz" value="-0.094" />
  <xacro:property name="mobile_robot_front_caster_wheel_base_dx" value="0.341346" />
  <xacro:property name="mobile_robot_back_caster_wheel_base_dx" value="-0.270154" />
  <xacro:property name="mobile_robot_caster_wheel_base_dy" value="0.203" />
  <xacro:property name="mobile_robot_caster_wheel_base_dz" value="${mobile_robot_caster_wheel_radius-mobile_robot_caster_wheel_dz}" />
  
  <xacro:property name="imu_stdev" value="0.00017" />
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <origin xyz="0.0 0.0 0.010" rpy="0 0 0" />
    <parent link="base_footprint" />
    <child link="base_link" />
    <axis xyz="0 0 1" />
  </joint>
  
  

  <link name="base_link">
    <visual>
      <origin xyz="${mobile_robot_act_wheel_dx} 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://mir_description/meshes/visual/mir_100_base.stl" />
      </geometry>
      <xacro:insert_block name="material_white" />
    </visual>
    <collision>
      <origin xyz="${mobile_robot_act_wheel_dx} 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://mir_description/meshes/collision/mir_100_base.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_front_laser_joint" type="fixed">
    <parent link="base_link" />
    <child link="front_laser_link" />
    <origin xyz="0.43 0.26000 0.30857" rpy="0.0 0.0 ${0.17311 * pi}" />   <!-- 0.415 -> 0.43   0.285000 -> 0.26  0.30857   /   0  0  0.25 *PI -> 0.17311 * pi-->
  </joint>
  <xacro:nanoscan_pro3 link="front_laser_link" topic="f_scan"/>

  <joint name="base_link_to_back_laser_joint" type="fixed">
    <parent link="base_link" />
    <child link="back_laser_link" /> 
    <origin xyz="-0.42 -0.26000 0.30857" rpy="0.0 0.0 ${-0.82356 * pi}" />  <!-- -0.415 -> -0.42  0.285000  -> 0.26  0.30857   /   0  0  -0.75 *PI -> -0.82356 * pi-->
  </joint>
  <xacro:nanoscan_pro3 link="back_laser_link" topic="b_scan"/>

  <xacro:actuated_wheel locationprefix="left" locationright="-1"/>
  <xacro:actuated_wheel locationprefix="right" locationright="1"/>
  <xacro:caster_wheel locationprefix="fl" locationright="-1" wheel_base_dx="${mobile_robot_front_caster_wheel_base_dx}"/>
  <xacro:caster_wheel locationprefix="fr" locationright="1" wheel_base_dx="${mobile_robot_front_caster_wheel_base_dx}"/>
  <xacro:caster_wheel locationprefix="bl" locationright="-1" wheel_base_dx="${mobile_robot_back_caster_wheel_base_dx}"/>
  <xacro:caster_wheel locationprefix="br" locationright="1" wheel_base_dx="${mobile_robot_back_caster_wheel_base_dx}"/>
  
  <xacro:mobile_robot_wheel_transmissions/>

  <joint name="base_link_to_imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin rpy="0 0 0" xyz="-0.015 0.0 0.18"/>
  </joint>
  
  <link name="imu_link" topic="/imu/data"/>
   
  
  <!-- IMU -->
    <joint name="base_link_to_imu_joint" type="fixed">
      <parent link="base_link" />
      <child link="imu_link" />
      <!-- same as real MiR -->
      <origin xyz="0.0 0.0 0.25" rpy="0 0 ${-pi/2}" /> <!-- 0 0 0.353  -->  
    </joint>

    <link name="imu_link" />

    <xacro:imu_gazebo link="imu_link" imu_topic="imu_data" update_rate="50.0" stdev="${imu_stdev}" />

    <!-- Create an alias for imu_link. This is necessary because the real MiR's
         TF has imu_link, but the imu_data topic is published in the imu_frame
         frame. -->
    <joint name="imu_link_to_imu_frame_joint" type="fixed">
      <parent link="imu_link" />
      <child link="imu_frame" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="imu_frame" />

</robot>
